server:
  port: 8101
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: http://10.24.12.27/zhoujian/springcloudinactivity.git #配置git仓库地址
          searchPaths: repo #配置仓库路径
          username: zhoujian #访问git仓库的用户名
          password: a1111111 #访问git仓库的用户密码
      label: master #配置仓库的分支
  rabbitmq:
    host: 10.24.12.15
    port: 5672
    username: admin
    password: admin
    virtualHost: /
    publisherConfirms: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh